on: [push]

jobs:
  Test_Job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test this action
        uses: ./
        with:
          access-token: ${{ secrets.CR_TOKEN }}
          source-charts-folder: 'test-charts'
          destination-repo: absaoss/helm-gh-pages-microservices
          destination-charts-folder: 'charts'
          destination-branch: gh-pages
